[server]
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
maxUploadSize = 500
port = 8501

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[logger]
level = "info"

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
